stages:
  - analyze

analyze_project:
  stage: analyze
  script:
    - flutter analyze
  tags:
    - flutter3

# Uncomment if there is at least 1 test already
# test_project:
#   stage: test
#   script:
#     - flutter test
#   tags:
#     - flutter3
