variables:
 FLAVOR: "prod"

stages:
  - analyze
  - archive

before_script:
  # Change the ownership of the project directory, so gradle run as a
  # non-rooter can create build folders in it.
  #
  # Since gitlab runner is run as root, the ownership of the project
  # directory checked out by the runner therefore belongs to root.
  # But we need to run gradle as the non-root user to be able to access the
  # gralde cache and android sdk typically installed by a non-rooter
  #
  # Hence the need for `chown` here.
  - chown -R moa .

analyze_project:
  stage: analyze
  script:
    - sudo -u moa flutter analyze
  tags:
    - ios
    - android

# Try generating at least Android (for now)
android:debug:
  stage: archive
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --flavor ${FLAVOR} --debug
  artifacts:
    paths:
      - "*.apk"
    expire_in: 1 day

android:release:
  stage: archive
  before_script:
    - flutter packages get
    - flutter clean
  script:
    - flutter doctor --android-licenses
    - flutter build apk --flavor ${FLAVOR} --release
  artifacts:
    paths:
      - "*.apk"
    expire_in: 1 day
