stages:
  - analyze
  - test

analyze_project:
  stage: analyze
  script:
    - fvm flutter analyze
  tags:
    - flutter3

test_project:
  stage: test
  script:
    - fvm flutter test
  tags:
    - flutter3
