name: thepcosprotocol_app
description: Ovie.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+91

environment:
  sdk: ">=3.0.0-0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # If running on an M1 based Macbook, you will need to do pod install manually in Terminal with this command:
  # arch -x86_64 pod install  (also the first time run this to fix ffi: sudo arch -x86_64 gem install ffi
  # Also note, when updating dependencies, you may need to increase the minimum platform at the top of the ios/Podfile
  # and then in Terminal run flutter clean and cd to ios folder and run pod update
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.5
  firebase_crashlytics: ^2.8.10
  url_launcher: ^6.1.5
  flutter_local_notifications: ^11.0.0
  shared_preferences: ^2.0.15
  device_info_plus: ^4.1.2
  connectivity: ^3.0.6
  onesignal_flutter: ^3.4.1
  package_info: ^2.0.2
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0
  provider: ^6.0.3
  flutter_widget_from_html_core: ^0.8.5+3
  flutter_inappwebview: 5.7.2+2
  fwfh_text_style: ^2.22.08+1
  better_player: ^0.0.83
  sqflite: ^2.0.3+1
  launch_review: ^3.0.1
  notification_permissions: ^0.6.1
  webview_flutter: ^3.0.4
  audioplayers: ^1.0.1
  full_screen_image_null_safe: ^2.0.0
  animations: ^2.0.4
  flutter_native_timezone: ^2.0.0
  rxdart: ^0.27.5
  auto_size_text: ^3.0.0
  dart_jsonwebtoken: ^2.6.3
  html_unescape: ^2.0.0
  stream_feed: ^0.6.0+2
  stream_feed_flutter_core: ^0.8.0
  image_picker: ^0.8.4+4
  timeago: ^3.0.2
  easy_image_viewer: ^1.2.1

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  build_runner: ^2.2.1
  sqflite_common_ffi: ^2.1.1+1
  flutter_driver:
    sdk: flutter
  dart_code_metrics: ^5.7.4
  intl_utils: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/html/

  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf

flutter_intl:
  enabled: true
