name: thepcosprotocol_app
description: The PCOS Protocol App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # If running on an M1 based Macbook, you will need to do pod install manually in Terminal with this command:
  # arch -x86_64 pod install  (also the first time run this to fix ffi: sudo arch -x86_64 gem install ffi
  # Also note, when updating dependencies, you may need to increase the minimum platform at the top of the ios/Podfile
  # and then in Terminal run flutter clean and cd to ios folder and run pod update
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^2.0.0
  url_launcher: ^6.0.3
  flutter_local_notifications: ^5.0.0+1
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  device_info: ^2.0.0
  connectivity: ^3.0.3
  onesignal_flutter: ^2.0.0
  package_info: ^0.4.3+2
  http: ^0.13.0
  flutter_secure_storage: ^3.3.5
  another_flushbar: ^1.10.5
  provider: ^4.3.2+3
  flutter_widget_from_html: ^0.6.0
  transparent_image: ^1.0.0
  better_player: ^0.0.60
  email_validator: ^1.0.6
  sqflite: ^2.0.0+3
  intercom_flutter: ^2.3.3
  launch_review: ^2.0.0
  carousel_slider: ^3.0.0
  flutter_native_timezone: ^1.0.4
  notification_permissions: ^0.4.8
  health: ^3.0.3
  avatar_glow: ^2.0.0
  native_pdf_view: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
    - family: Courgette
      fonts:
        - asset: fonts/Courgette-Regular.ttf

flutter_intl:
  enabled: true
